import {
	PUBLIC_USER_COLLECTION_ID,
	PUBLIC_KRELLO_DB_ID,
	PUBLIC_PROFILE_PIC_BUCKET_ID,
	PUBLIC_BOARDS_BUCKET_ID,
	PUBLIC_BOARDS_COLLECTION_ID,
	PUBLIC_TASK_COLLECTION_ID,
	PUBLIC_STATUS_COLLECTION_ID,
	PUBLIC_PRIORITY_COLLECTION_ID,
	PUBLIC_LABELS_COLLECTION_ID,
	PUBLIC_TASKS_BUCKED_ID,
	PUBLIC_COMMENTS_COLLECTION_ID,
} from '$env/static/public';

const APPWRITE_CONST = Object.freeze({
	USER_COLLECTION_ID: PUBLIC_USER_COLLECTION_ID,
	BOARDS_COLLECTION_ID: PUBLIC_BOARDS_COLLECTION_ID,
	KRELLO_DB_ID: PUBLIC_KRELLO_DB_ID,
	PROFILE_PIC_BUCKET_ID: PUBLIC_PROFILE_PIC_BUCKET_ID,
	BOARDS_BUCKET_ID: PUBLIC_BOARDS_BUCKET_ID,
	TASK_COLLECTION_ID: PUBLIC_TASK_COLLECTION_ID,
	STATUS_COLLECTION_ID: PUBLIC_STATUS_COLLECTION_ID,
	PRIORITY_COLLECTION_ID: PUBLIC_PRIORITY_COLLECTION_ID,
	LABELS_COLLECTION_ID: PUBLIC_LABELS_COLLECTION_ID,
	TASKS_BUCKED_ID: PUBLIC_TASKS_BUCKED_ID,
	TASK_CHANNEL: `databases.${PUBLIC_KRELLO_DB_ID}.collections.${PUBLIC_TASK_COLLECTION_ID}.documents`,
	COMMENTS_COLLECTION_ID: PUBLIC_COMMENTS_COLLECTION_ID,
	COMMENTS_CHANNEL: `databases.${PUBLIC_KRELLO_DB_ID}.collections.${PUBLIC_COMMENTS_COLLECTION_ID}.documents`,
	BOARDS_CHANNEL: `databases.${PUBLIC_KRELLO_DB_ID}.collections.${PUBLIC_BOARDS_COLLECTION_ID}.documents`,
});

export default APPWRITE_CONST;
