import {
	PUBLIC_USER_COLLECTION_ID,
	PUBLIC_KRELLO_DB_ID,
	PUBLIC_PROFILE_PIC_BUCKET_ID,
	PUBLIC_BOARDS_BUCKET_ID,
	PUBLIC_BOARDS_COLLECTION_ID,
} from '$env/static/public';

const APPWRITE_CONST = Object.freeze({
	USER_COLLECTION_ID: PUBLIC_USER_COLLECTION_ID,
	BOARDS_COLLECTION_ID: PUBLIC_BOARDS_COLLECTION_ID,
	KRELLO_DB_ID: PUBLIC_KRELLO_DB_ID,
	PROFILE_PIC_BUCKET_ID: PUBLIC_PROFILE_PIC_BUCKET_ID,
	BOARDS_BUCKET_ID: PUBLIC_BOARDS_BUCKET_ID,
});

export default APPWRITE_CONST;
